sudo: true
dist: xenial
services: docker
before_install:
  - lsb_release -a
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y python3 python3-pip
  - python3 -m pip install --user pipenv
install: pipenv install --dev
script: pipenv run pytest
